### PR TITLE
Implement #4, "Pull data from Meetup API"

### PR DESCRIPTION
**Pull request by woolsweater**
This implements #4, adding an "/events" route to the `Droplet` to display a new page listing future group events from our Meetup.com account. The "Events" page is laid out in Resources/Views/upcoming-events.mustache, with an accompanying stylesheet in Public/css/. A link to the new page is included in the nav.

The route handler creates a `MeetupAPI` struct, which connects to api.meetup.com and pulls down future events.

A private `Configuration` struct supplies `MeetupAPI` with the appropriate URL information. It gets the URL pieces from the Config/meetup.json file, accessing it via the active `Droplet`'s `Config` object. (The `Droplet` aleady knows where the config files are, rather than us having to find them again.) The `Droplet`'s `Config` is passed in to `MeetupAPI` on its creation.

The events are provided by Meetup.com as a JSON array. The JSON objects are unpacked into a parallel array of `MeetupEvent` structs, which is passed back out to the route handler to be used as the context for the view. `MeetupEvent` retains only the fields that are needed for the page's template (this is of course open to further expansion).

The page's template uses some Mustache filters to make numerical data look nice, formatting dates and pluralizing "person"/"people" for the RSVP count. `MeetupEvent` also conforms to `MustacheBoxable` so that it can be included directly in the rendering context.

(This comment is largely a rehash of the commit messages; hopefully everything is clear.)

### CODE REVIEW

**Comment by boek** [comment]
Awesome stuff @woolsweater! I'll take a look at this after work 🙌

**Review by aranasaurus — COMMENTED** [review]
Wow! Thanks for all the well-documented code, nice work!

**Comment by aranasaurus** [comment]
Since I merged some PRs this one now has some conflicts to be resolved, but I approve of this PR, and will wait for @boek to review it since he's more familiar with this piece. But consider this my 👍!

**Comment by woolsweater** [comment]
Thanks!

Merge conflicts have been resolved. (Sorry about the double-commit for that. I can squash those if necessary.)

**Comment by boek** [comment]
Looks good to me 👍

**Pull request merged**
